version: "3"
services:
  app:
    build:
      context: ./blog_api
      dockerfile: Dockerfile
    entrypoint: ["./wait.sh"]
    depends-on: #links:
      - db
    ports:
      - "8080:8000"

  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
